// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

/* verilator lint_off WIDTHEXPAND */
/* verilator lint_off WIDTHTRUNC */
module axi4_tester (
        ap_clk,
        ap_rst_n,
        m_axi_data_in_out_V_AWVALID,
        m_axi_data_in_out_V_AWREADY,
        m_axi_data_in_out_V_AWADDR,
        m_axi_data_in_out_V_AWID,
        m_axi_data_in_out_V_AWLEN,
        m_axi_data_in_out_V_AWSIZE,
        m_axi_data_in_out_V_AWBURST,
        m_axi_data_in_out_V_AWLOCK,
        m_axi_data_in_out_V_AWCACHE,
        m_axi_data_in_out_V_AWPROT,
        m_axi_data_in_out_V_AWQOS,
        m_axi_data_in_out_V_AWREGION,
        m_axi_data_in_out_V_AWUSER,
        m_axi_data_in_out_V_WVALID,
        m_axi_data_in_out_V_WREADY,
        m_axi_data_in_out_V_WDATA,
        m_axi_data_in_out_V_WSTRB,
        m_axi_data_in_out_V_WLAST,
        m_axi_data_in_out_V_WID,
        m_axi_data_in_out_V_WUSER,
        m_axi_data_in_out_V_ARVALID,
        m_axi_data_in_out_V_ARREADY,
        m_axi_data_in_out_V_ARADDR,
        m_axi_data_in_out_V_ARID,
        m_axi_data_in_out_V_ARLEN,
        m_axi_data_in_out_V_ARSIZE,
        m_axi_data_in_out_V_ARBURST,
        m_axi_data_in_out_V_ARLOCK,
        m_axi_data_in_out_V_ARCACHE,
        m_axi_data_in_out_V_ARPROT,
        m_axi_data_in_out_V_ARQOS,
        m_axi_data_in_out_V_ARREGION,
        m_axi_data_in_out_V_ARUSER,
        m_axi_data_in_out_V_RVALID,
        m_axi_data_in_out_V_RREADY,
        m_axi_data_in_out_V_RDATA,
        m_axi_data_in_out_V_RLAST,
        m_axi_data_in_out_V_RID,
        m_axi_data_in_out_V_RUSER,
        m_axi_data_in_out_V_RRESP,
        m_axi_data_in_out_V_BVALID,
        m_axi_data_in_out_V_BREADY,
        m_axi_data_in_out_V_BRESP,
        m_axi_data_in_out_V_BID,
        m_axi_data_in_out_V_BUSER,
        correct_V,
        correct_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;
parameter    C_M_AXI_DATA_IN_OUT_V_ID_WIDTH = 1;
parameter    C_M_AXI_DATA_IN_OUT_V_ADDR_WIDTH = 32;
parameter    C_M_AXI_DATA_IN_OUT_V_DATA_WIDTH = 32;
parameter    C_M_AXI_DATA_IN_OUT_V_AWUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_IN_OUT_V_ARUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_IN_OUT_V_WUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_IN_OUT_V_RUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_IN_OUT_V_BUSER_WIDTH = 1;
parameter    C_M_AXI_DATA_IN_OUT_V_TARGET_ADDR = 0;
parameter    C_M_AXI_DATA_IN_OUT_V_USER_VALUE = 0;
parameter    C_M_AXI_DATA_IN_OUT_V_PROT_VALUE = 0;
parameter    C_M_AXI_DATA_IN_OUT_V_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_DATA_IN_OUT_V_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_data_in_out_V_AWVALID;
input   m_axi_data_in_out_V_AWREADY;
output  [C_M_AXI_DATA_IN_OUT_V_ADDR_WIDTH - 1:0] m_axi_data_in_out_V_AWADDR;
output  [C_M_AXI_DATA_IN_OUT_V_ID_WIDTH - 1:0] m_axi_data_in_out_V_AWID;
output  [7:0] m_axi_data_in_out_V_AWLEN;
output  [2:0] m_axi_data_in_out_V_AWSIZE;
output  [1:0] m_axi_data_in_out_V_AWBURST;
output  [1:0] m_axi_data_in_out_V_AWLOCK;
output  [3:0] m_axi_data_in_out_V_AWCACHE;
output  [2:0] m_axi_data_in_out_V_AWPROT;
output  [3:0] m_axi_data_in_out_V_AWQOS;
output  [3:0] m_axi_data_in_out_V_AWREGION;
output  [C_M_AXI_DATA_IN_OUT_V_AWUSER_WIDTH - 1:0] m_axi_data_in_out_V_AWUSER;
output   m_axi_data_in_out_V_WVALID;
input   m_axi_data_in_out_V_WREADY;
output  [C_M_AXI_DATA_IN_OUT_V_DATA_WIDTH - 1:0] m_axi_data_in_out_V_WDATA;
output  [C_M_AXI_DATA_IN_OUT_V_WSTRB_WIDTH - 1:0] m_axi_data_in_out_V_WSTRB;
output   m_axi_data_in_out_V_WLAST;
output  [C_M_AXI_DATA_IN_OUT_V_ID_WIDTH - 1:0] m_axi_data_in_out_V_WID;
output  [C_M_AXI_DATA_IN_OUT_V_WUSER_WIDTH - 1:0] m_axi_data_in_out_V_WUSER;
output   m_axi_data_in_out_V_ARVALID;
input   m_axi_data_in_out_V_ARREADY;
output  [C_M_AXI_DATA_IN_OUT_V_ADDR_WIDTH - 1:0] m_axi_data_in_out_V_ARADDR;
output  [C_M_AXI_DATA_IN_OUT_V_ID_WIDTH - 1:0] m_axi_data_in_out_V_ARID;
output  [7:0] m_axi_data_in_out_V_ARLEN;
output  [2:0] m_axi_data_in_out_V_ARSIZE;
output  [1:0] m_axi_data_in_out_V_ARBURST;
output  [1:0] m_axi_data_in_out_V_ARLOCK;
output  [3:0] m_axi_data_in_out_V_ARCACHE;
output  [2:0] m_axi_data_in_out_V_ARPROT;
output  [3:0] m_axi_data_in_out_V_ARQOS;
output  [3:0] m_axi_data_in_out_V_ARREGION;
output  [C_M_AXI_DATA_IN_OUT_V_ARUSER_WIDTH - 1:0] m_axi_data_in_out_V_ARUSER;
input   m_axi_data_in_out_V_RVALID;
output   m_axi_data_in_out_V_RREADY;
input  [C_M_AXI_DATA_IN_OUT_V_DATA_WIDTH - 1:0] m_axi_data_in_out_V_RDATA;
input   m_axi_data_in_out_V_RLAST;
input  [C_M_AXI_DATA_IN_OUT_V_ID_WIDTH - 1:0] m_axi_data_in_out_V_RID;
input  [C_M_AXI_DATA_IN_OUT_V_RUSER_WIDTH - 1:0] m_axi_data_in_out_V_RUSER;
input  [1:0] m_axi_data_in_out_V_RRESP;
input   m_axi_data_in_out_V_BVALID;
output   m_axi_data_in_out_V_BREADY;
input  [1:0] m_axi_data_in_out_V_BRESP;
input  [C_M_AXI_DATA_IN_OUT_V_ID_WIDTH - 1:0] m_axi_data_in_out_V_BID;
input  [C_M_AXI_DATA_IN_OUT_V_BUSER_WIDTH - 1:0] m_axi_data_in_out_V_BUSER;
output  [0:0] correct_V;
output   correct_V_ap_vld;

reg correct_V_ap_vld;

 reg    ap_rst_n_inv;
reg   [9:0] addr_address0;
reg    addr_ce0;
wire   [9:0] addr_q0;
reg   [9:0] test_data_V_address0;
reg    test_data_V_ce0;
wire   [31:0] test_data_V_q0;
reg    data_in_out_V_blk_n_AW;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state4;
reg    data_in_out_V_blk_n_W;
wire    ap_CS_fsm_state5;
reg    data_in_out_V_blk_n_B;
wire    ap_CS_fsm_state10;
reg    data_in_out_V_blk_n_AR;
wire    ap_CS_fsm_state13;
reg    data_in_out_V_blk_n_R;
wire    ap_CS_fsm_state20;
reg    data_in_out_V_AWVALID;
wire    data_in_out_V_AWREADY;
wire   [31:0] data_in_out_V_AWADDR;
reg    data_in_out_V_WVALID;
wire    data_in_out_V_WREADY;
reg    data_in_out_V_ARVALID;
wire    data_in_out_V_ARREADY;
wire   [31:0] data_in_out_V_ARADDR;
wire    data_in_out_V_RVALID;
reg    data_in_out_V_RREADY;
wire   [31:0] data_in_out_V_RDATA;
wire    data_in_out_V_RLAST;
wire   [0:0] data_in_out_V_RID;
wire   [0:0] data_in_out_V_RUSER;
wire   [1:0] data_in_out_V_RRESP;
wire    data_in_out_V_BVALID;
reg    data_in_out_V_BREADY;
wire   [1:0] data_in_out_V_BRESP;
wire   [0:0] data_in_out_V_BID;
wire   [0:0] data_in_out_V_BUSER;
reg   [9:0] reg_213;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state12;
wire   [10:0] i_fu_223_p2;
reg   [10:0] i_reg_301;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln13_fu_217_p2;
reg   [31:0] test_data_V_load_reg_316;
wire   [10:0] i_1_fu_252_p2;
reg   [10:0] i_1_reg_330;
wire    ap_CS_fsm_state11;
wire   [63:0] zext_ln22_fu_258_p1;
reg   [63:0] zext_ln22_reg_335;
wire   [0:0] icmp_ln19_fu_246_p2;
reg   [31:0] data_in_out_V_addr_1_1_reg_351;
wire   [10:0] i_2_fu_280_p2;
reg   [10:0] i_2_reg_359;
wire    ap_CS_fsm_state22;
wire   [0:0] icmp_ln26_fu_274_p2;
reg   [9:0] data_from_mem_V_address0;
reg    data_from_mem_V_ce0;
reg    data_from_mem_V_we0;
wire   [31:0] data_from_mem_V_q0;
reg   [10:0] i_0_reg_166;
wire    ap_CS_fsm_state1;
reg   [10:0] i1_0_reg_177;
wire    ap_CS_fsm_state21;
reg   [10:0] i2_0_reg_188;
wire    ap_CS_fsm_state23;
wire   [0:0] icmp_ln883_fu_292_p2;
reg   [0:0] storemerge_reg_199;
wire   [63:0] zext_ln16_fu_229_p1;
wire   [63:0] zext_ln28_fu_286_p1;
wire   [63:0] zext_ln16_1_fu_235_p1;
wire   [63:0] zext_ln22_1_fu_263_p1;
wire    ap_CS_fsm_state24;
reg   [23:0] ap_NS_fsm;

// power-on initialization
initial begin
   ap_CS_fsm = 24'd1;
end

axi4_tester_addr #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
addr_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(addr_address0),
    .ce0(addr_ce0),
    .q0(addr_q0)
);

axi4_tester_test_data_V #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
test_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(test_data_V_address0),
    .ce0(test_data_V_ce0),
    .q0(test_data_V_q0)
);

axi4_tester_data_in_out_V_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_DATA_IN_OUT_V_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_DATA_IN_OUT_V_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_DATA_IN_OUT_V_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_DATA_IN_OUT_V_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_DATA_IN_OUT_V_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_DATA_IN_OUT_V_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_DATA_IN_OUT_V_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_DATA_IN_OUT_V_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_DATA_IN_OUT_V_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_DATA_IN_OUT_V_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_DATA_IN_OUT_V_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_DATA_IN_OUT_V_CACHE_VALUE ))
axi4_tester_data_in_out_V_m_axi_U(
    .AWVALID(m_axi_data_in_out_V_AWVALID),
    .AWREADY(m_axi_data_in_out_V_AWREADY),
    .AWADDR(m_axi_data_in_out_V_AWADDR),
    .AWID(m_axi_data_in_out_V_AWID),
    .AWLEN(m_axi_data_in_out_V_AWLEN),
    .AWSIZE(m_axi_data_in_out_V_AWSIZE),
    .AWBURST(m_axi_data_in_out_V_AWBURST),
    .AWLOCK(m_axi_data_in_out_V_AWLOCK),
    .AWCACHE(m_axi_data_in_out_V_AWCACHE),
    .AWPROT(m_axi_data_in_out_V_AWPROT),
    .AWQOS(m_axi_data_in_out_V_AWQOS),
    .AWREGION(m_axi_data_in_out_V_AWREGION),
    .AWUSER(m_axi_data_in_out_V_AWUSER),
    .WVALID(m_axi_data_in_out_V_WVALID),
    .WREADY(m_axi_data_in_out_V_WREADY),
    .WDATA(m_axi_data_in_out_V_WDATA),
    .WSTRB(m_axi_data_in_out_V_WSTRB),
    .WLAST(m_axi_data_in_out_V_WLAST),
    .WID(m_axi_data_in_out_V_WID),
    .WUSER(m_axi_data_in_out_V_WUSER),
    .ARVALID(m_axi_data_in_out_V_ARVALID),
    .ARREADY(m_axi_data_in_out_V_ARREADY),
    .ARADDR(m_axi_data_in_out_V_ARADDR),
    .ARID(m_axi_data_in_out_V_ARID),
    .ARLEN(m_axi_data_in_out_V_ARLEN),
    .ARSIZE(m_axi_data_in_out_V_ARSIZE),
    .ARBURST(m_axi_data_in_out_V_ARBURST),
    .ARLOCK(m_axi_data_in_out_V_ARLOCK),
    .ARCACHE(m_axi_data_in_out_V_ARCACHE),
    .ARPROT(m_axi_data_in_out_V_ARPROT),
    .ARQOS(m_axi_data_in_out_V_ARQOS),
    .ARREGION(m_axi_data_in_out_V_ARREGION),
    .ARUSER(m_axi_data_in_out_V_ARUSER),
    .RVALID(m_axi_data_in_out_V_RVALID),
    .RREADY(m_axi_data_in_out_V_RREADY),
    .RDATA(m_axi_data_in_out_V_RDATA),
    .RLAST(m_axi_data_in_out_V_RLAST),
    .RID(m_axi_data_in_out_V_RID),
    .RUSER(m_axi_data_in_out_V_RUSER),
    .RRESP(m_axi_data_in_out_V_RRESP),
    .BVALID(m_axi_data_in_out_V_BVALID),
    .BREADY(m_axi_data_in_out_V_BREADY),
    .BRESP(m_axi_data_in_out_V_BRESP),
    .BID(m_axi_data_in_out_V_BID),
    .BUSER(m_axi_data_in_out_V_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(data_in_out_V_ARVALID),
    .I_ARREADY(data_in_out_V_ARREADY),
    .I_ARADDR(data_in_out_V_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(data_in_out_V_RVALID),
    .I_RREADY(data_in_out_V_RREADY),
    .I_RDATA(data_in_out_V_RDATA),
    .I_RID(data_in_out_V_RID),
    .I_RUSER(data_in_out_V_RUSER),
    .I_RRESP(data_in_out_V_RRESP),
    .I_RLAST(data_in_out_V_RLAST),
    .I_AWVALID(data_in_out_V_AWVALID),
    .I_AWREADY(data_in_out_V_AWREADY),
    .I_AWADDR(data_in_out_V_AWADDR),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(data_in_out_V_WVALID),
    .I_WREADY(data_in_out_V_WREADY),
    .I_WDATA(test_data_V_load_reg_316),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(data_in_out_V_BVALID),
    .I_BREADY(data_in_out_V_BREADY),
    .I_BRESP(data_in_out_V_BRESP),
    .I_BID(data_in_out_V_BID),
    .I_BUSER(data_in_out_V_BUSER)
);

axi4_tester_data_from_mem_V #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
data_from_mem_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(data_from_mem_V_address0),
    .ce0(data_from_mem_V_ce0),
    .we0(data_from_mem_V_we0),
    .d0(data_in_out_V_addr_1_1_reg_351),
    .q0(data_from_mem_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln13_fu_217_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_0_reg_177 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        i1_0_reg_177 <= i_1_reg_330;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln19_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        i2_0_reg_188 <= 11'd0;
    end else if (((icmp_ln883_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
        i2_0_reg_188 <= i_2_reg_359;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        i_0_reg_166 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state10) & (data_in_out_V_BVALID == 1'b1))) begin
        i_0_reg_166 <= i_reg_301;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_274_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        storemerge_reg_199 <= 1'd1;
    end else if (((icmp_ln883_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        storemerge_reg_199 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state20) & (data_in_out_V_RVALID == 1'b1))) begin
        data_in_out_V_addr_1_1_reg_351 <= data_in_out_V_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        i_1_reg_330 <= i_1_fu_252_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        i_2_reg_359 <= i_2_fu_280_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_301 <= i_fu_223_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_213 <= addr_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        test_data_V_load_reg_316 <= test_data_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln19_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        zext_ln22_reg_335[10 : 0] <= zext_ln22_fu_258_p1[10 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        addr_address0 = zext_ln22_fu_258_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        addr_address0 = zext_ln16_fu_229_p1;
    end else begin
        addr_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        addr_ce0 = 1'b1;
    end else begin
        addr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        correct_V_ap_vld = 1'b1;
    end else begin
        correct_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        data_from_mem_V_address0 = zext_ln28_fu_286_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        data_from_mem_V_address0 = zext_ln22_reg_335;
    end else begin
        data_from_mem_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        data_from_mem_V_ce0 = 1'b1;
    end else begin
        data_from_mem_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        data_from_mem_V_we0 = 1'b1;
    end else begin
        data_from_mem_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (data_in_out_V_ARREADY == 1'b1))) begin
        data_in_out_V_ARVALID = 1'b1;
    end else begin
        data_in_out_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (data_in_out_V_AWREADY == 1'b1))) begin
        data_in_out_V_AWVALID = 1'b1;
    end else begin
        data_in_out_V_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (data_in_out_V_BVALID == 1'b1))) begin
        data_in_out_V_BREADY = 1'b1;
    end else begin
        data_in_out_V_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) & (data_in_out_V_RVALID == 1'b1))) begin
        data_in_out_V_RREADY = 1'b1;
    end else begin
        data_in_out_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (data_in_out_V_WREADY == 1'b1))) begin
        data_in_out_V_WVALID = 1'b1;
    end else begin
        data_in_out_V_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        data_in_out_V_blk_n_AR = m_axi_data_in_out_V_ARREADY;
    end else begin
        data_in_out_V_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        data_in_out_V_blk_n_AW = m_axi_data_in_out_V_AWREADY;
    end else begin
        data_in_out_V_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        data_in_out_V_blk_n_B = m_axi_data_in_out_V_BVALID;
    end else begin
        data_in_out_V_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        data_in_out_V_blk_n_R = m_axi_data_in_out_V_RVALID;
    end else begin
        data_in_out_V_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        data_in_out_V_blk_n_W = m_axi_data_in_out_V_WREADY;
    end else begin
        data_in_out_V_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        test_data_V_address0 = zext_ln28_fu_286_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        test_data_V_address0 = zext_ln16_fu_229_p1;
    end else begin
        test_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state2))) begin
        test_data_V_ce0 = 1'b1;
    end else begin
        test_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln13_fu_217_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (data_in_out_V_AWREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (data_in_out_V_WREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (data_in_out_V_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((icmp_ln19_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (data_in_out_V_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (data_in_out_V_RVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state22 : begin
            if (((icmp_ln26_fu_274_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((icmp_ln883_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign correct_V = storemerge_reg_199;

assign data_in_out_V_ARADDR = zext_ln22_1_fu_263_p1;

assign data_in_out_V_AWADDR = zext_ln16_1_fu_235_p1;

assign i_1_fu_252_p2 = (i1_0_reg_177 + 11'd1);

assign i_2_fu_280_p2 = (i2_0_reg_188 + 11'd1);

assign i_fu_223_p2 = (i_0_reg_166 + 11'd1);

assign icmp_ln13_fu_217_p2 = ((i_0_reg_166 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_246_p2 = ((i1_0_reg_177 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_274_p2 = ((i2_0_reg_188 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln883_fu_292_p2 = ((data_from_mem_V_q0 == test_data_V_q0) ? 1'b1 : 1'b0);

assign zext_ln16_1_fu_235_p1 = reg_213;

assign zext_ln16_fu_229_p1 = i_0_reg_166;

assign zext_ln22_1_fu_263_p1 = reg_213;

assign zext_ln22_fu_258_p1 = i1_0_reg_177;

assign zext_ln28_fu_286_p1 = i2_0_reg_188;

always @ (posedge ap_clk) begin
    zext_ln22_reg_335[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //axi4_tester
