// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_axi4_ram.h for the primary calling header

#ifndef VERILATED_VTB_AXI4_RAM_TB_AXI4_RAM_H_
#define VERILATED_VTB_AXI4_RAM_TB_AXI4_RAM_H_  // guard

#include "verilated.h"


class Vtb_axi4_ram__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_axi4_ram_tb_axi4_ram final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        CData/*7:0*/ __PVT__s_axi_awid;
        CData/*0:0*/ __PVT__s_axi_awvalid;
        CData/*7:0*/ __PVT__s_axi_arid;
        CData/*0:0*/ correct_V;
        CData/*0:0*/ correct_V_ap_vld;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__m_axi_data_in_out_V_RUSER;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__m_axi_data_in_out_V_BUSER;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__data_in_out_V_BVALID;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__data_in_out_V_BRESP;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__icmp_ln883_fu_292_p2;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__storemerge_reg_199;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__I_AWVALID;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__I_WVALID;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__I_BREADY;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__I_ARVALID;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__I_RREADY;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__AWREADY_Dummy;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__wreq_throttl__DOT__genblk1__DOT__throttl_cnt;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__rs2f_wreq_ack;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__sect_end_buf;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__zero_len_event;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__negative_len_event;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__invalid_len_event;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__invalid_len_event_reg1;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__invalid_len_event_reg2;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq_valid;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq_valid_buf;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__AWVALID_Dummy;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__last_sect_buf;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__ready_for_wreq;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__wreq_handling;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__first_sect;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__last_sect;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__next_sect;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__len_cnt;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__burst_len;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__beat_valid;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__burst_valid;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_burst_ready;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__WVALID_Dummy;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__WLAST_Dummy;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__aw2b_bdata;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bresp_tmp;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__next_resp;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp_ready;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__need_wrsp;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__resp_ready;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__could_multi_bursts__DOT__awlen_buf;
        CData/*5:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__could_multi_bursts__DOT__loop_cnt;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__could_multi_bursts__DOT__sect_handling;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__could_multi_bursts__DOT__last_loop;
        CData/*3:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__strb_buf;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__ready_for_data;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__rs_wreq__DOT__s_ready_t;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__rs_wreq__DOT__state;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__rs_wreq__DOT__next;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq__DOT__rdreq;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq__DOT__push;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq__DOT__pop;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq__DOT__data_vld;
        CData/*2:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq__DOT__pout;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__if_read;
    };
    struct {
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__waddr;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__raddr;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__wnext;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__rnext;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__push;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__pop;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__usedw;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__full_n;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__empty_n;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__show_ahead;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__dout_valid;
        CData/*1:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp__DOT____Vlvbound_h233b9095__0;
        CData/*1:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp__DOT____Vxrand___0;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp__DOT__wrreq;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp__DOT__push;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp__DOT__pop;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp__DOT__data_vld;
        CData/*3:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp__DOT__pout;
        CData/*1:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp_to_user__DOT____Vlvbound_hfd64ca52__0;
        CData/*1:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp_to_user__DOT____Vxrand___0;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp_to_user__DOT__wrreq;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp_to_user__DOT__push;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp_to_user__DOT__pop;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp_to_user__DOT__data_vld;
        CData/*2:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp_to_user__DOT__pout;
        CData/*7:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__fifo_burst__DOT____Vlvbound_h2fb6c94e__0;
        CData/*7:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__fifo_burst__DOT____Vxrand___0;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__fifo_burst__DOT__rdreq;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__fifo_burst__DOT__data;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__fifo_burst__DOT__push;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__fifo_burst__DOT__pop;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__fifo_burst__DOT__data_vld;
        CData/*2:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__fifo_burst__DOT__pout;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs2f_rreq_ack;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__sect_end_buf;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__invalid_len_event;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__invalid_len_event_reg1;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__invalid_len_event_reg2;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq_valid;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq_valid_buf;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_resp_w;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__ARVALID_Dummy;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__ready_for_rreq;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rreq_handling;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__first_sect;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__last_sect;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__next_sect;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__len_cnt;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__ar2r_rdata;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__resp_buf;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__need_rlast;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl_ready;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__burst_valid;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__next_burst;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rdata_valid_t;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__could_multi_bursts__DOT__arlen_buf;
        CData/*5:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__could_multi_bursts__DOT__loop_cnt;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__could_multi_bursts__DOT__sect_handling;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__could_multi_bursts__DOT__last_loop;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__bus_equal_gen__DOT__ready_for_data;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rreq__DOT__s_ready_t;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rreq__DOT__state;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rreq__DOT__next;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq__DOT__rdreq;
    };
    struct {
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq__DOT__push;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq__DOT__pop;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq__DOT__data_vld;
        CData/*2:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq__DOT__pout;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__if_read;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__waddr;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__raddr;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__wnext;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__rnext;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__push;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__pop;
        CData/*7:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__usedw;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__full_n;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__empty_n;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__show_ahead;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__dout_valid;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rdata__DOT__s_ready_t;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rdata__DOT__state;
        CData/*1:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rdata__DOT__next;
        CData/*1:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl__DOT____Vlvbound_h233b9095__0;
        CData/*1:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl__DOT____Vxrand___0;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl__DOT__rdreq;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl__DOT__wrreq;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl__DOT__push;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl__DOT__pop;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl__DOT__data_vld;
        CData/*3:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl__DOT__pout;
        CData/*0:0*/ __PVT__axi4_tester_inst__DOT__data_from_mem_V_U__DOT__axi4_tester_data_from_mem_V_ram_U__DOT__ce0;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__read_state_reg;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__read_state_next;
        CData/*1:0*/ __PVT__axi_ram_inst__DOT__write_state_reg;
        CData/*1:0*/ __PVT__axi_ram_inst__DOT__write_state_next;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__mem_wr_en;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__mem_rd_en;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__read_id_reg;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__read_id_next;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__read_count_reg;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__read_count_next;
        CData/*2:0*/ __PVT__axi_ram_inst__DOT__read_size_reg;
        CData/*2:0*/ __PVT__axi_ram_inst__DOT__read_size_next;
        CData/*1:0*/ __PVT__axi_ram_inst__DOT__read_burst_reg;
        CData/*1:0*/ __PVT__axi_ram_inst__DOT__read_burst_next;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__write_id_reg;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__write_id_next;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__write_count_reg;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__write_count_next;
        CData/*2:0*/ __PVT__axi_ram_inst__DOT__write_size_reg;
        CData/*2:0*/ __PVT__axi_ram_inst__DOT__write_size_next;
        CData/*1:0*/ __PVT__axi_ram_inst__DOT__write_burst_reg;
        CData/*1:0*/ __PVT__axi_ram_inst__DOT__write_burst_next;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_awready_reg;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_awready_next;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_wready_reg;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_wready_next;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__s_axi_bid_reg;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__s_axi_bid_next;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_bvalid_reg;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_bvalid_next;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_arready_reg;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_arready_next;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__s_axi_rid_reg;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__s_axi_rid_next;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_rlast_reg;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_rlast_next;
    };
    struct {
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_rvalid_reg;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_rvalid_next;
        CData/*7:0*/ __PVT__axi_ram_inst__DOT__s_axi_rid_pipe_reg;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_rlast_pipe_reg;
        CData/*0:0*/ __PVT__axi_ram_inst__DOT__s_axi_rvalid_pipe_reg;
        SData/*9:0*/ axi4_tester_inst__DOT____Vxrand___2;
        SData/*9:0*/ axi4_tester_inst__DOT____Vxrand___1;
        SData/*9:0*/ axi4_tester_inst__DOT____Vxrand___0;
        SData/*9:0*/ __PVT__axi4_tester_inst__DOT__addr_q0;
        SData/*9:0*/ __PVT__axi4_tester_inst__DOT__reg_213;
        SData/*10:0*/ __PVT__axi4_tester_inst__DOT__i_reg_301;
        SData/*10:0*/ __PVT__axi4_tester_inst__DOT__i_1_reg_330;
        SData/*10:0*/ __PVT__axi4_tester_inst__DOT__i_2_reg_359;
        SData/*10:0*/ __PVT__axi4_tester_inst__DOT__i_0_reg_166;
        SData/*10:0*/ __PVT__axi4_tester_inst__DOT__i1_0_reg_177;
        SData/*10:0*/ __PVT__axi4_tester_inst__DOT__i2_0_reg_188;
        SData/*9:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__sect_len_buf;
        SData/*9:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__beat_len_buf;
        SData/*9:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__sect_len_buf;
        SData/*9:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__beat_len_buf;
        SData/*9:0*/ __PVT__axi4_tester_inst__DOT__data_from_mem_V_U__DOT__axi4_tester_data_from_mem_V_ram_U__DOT__addr0;
        SData/*15:0*/ __PVT__axi_ram_inst__DOT__read_addr_reg;
        SData/*15:0*/ __PVT__axi_ram_inst__DOT__read_addr_next;
        SData/*15:0*/ __PVT__axi_ram_inst__DOT__write_addr_reg;
        SData/*15:0*/ __PVT__axi_ram_inst__DOT__write_addr_next;
        IData/*23:0*/ axi4_tester_inst__DOT____Vxrand___3;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__test_data_V_q0;
        IData/*23:0*/ __PVT__axi4_tester_inst__DOT__ap_CS_fsm;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__test_data_V_load_reg_316;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__data_in_out_V_addr_1_1_reg_351;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__data_from_mem_V_q0;
        IData/*23:0*/ __PVT__axi4_tester_inst__DOT__ap_NS_fsm;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__wreq_throttl__DOT__log2__Vstatic__n;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__wreq_throttl__DOT__log2__Vstatic__m;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__calc_data_width__Vstatic__y;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__log2__Vstatic__n;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__log2__Vstatic__m;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__align_len;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__awaddr_tmp;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__start_addr;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__start_addr_buf;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__end_addr_buf;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__sect_addr_buf;
        IData/*19:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__sect_cnt;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__could_multi_bursts__DOT__awaddr_buf;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__data_buf;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq__DOT__i;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp__DOT__i;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp_to_user__DOT__i;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__fifo_burst__DOT__i;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__calc_data_width__Vstatic__y;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__log2__Vstatic__n;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__log2__Vstatic__m;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__align_len;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__araddr_tmp;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__start_addr;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__start_addr_buf;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__end_addr_buf;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__sect_addr_buf;
        IData/*19:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__sect_cnt;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__could_multi_bursts__DOT__araddr_buf;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__bus_equal_gen__DOT__data_buf;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq__DOT__i;
        IData/*31:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl__DOT__i;
    };
    struct {
        IData/*31:0*/ __PVT__axi_ram_inst__DOT__s_axi_rdata_reg;
        IData/*31:0*/ __PVT__axi_ram_inst__DOT__s_axi_rdata_next;
        IData/*31:0*/ __PVT__axi_ram_inst__DOT__s_axi_rdata_pipe_reg;
        IData/*31:0*/ __PVT__axi_ram_inst__DOT__i;
        IData/*31:0*/ __PVT__axi_ram_inst__DOT__j;
        QData/*63:0*/ __PVT__axi4_tester_inst__DOT__zext_ln22_reg_335;
        QData/*63:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq_data;
        QData/*63:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__rs_wreq__DOT__data_p1;
        QData/*63:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__rs_wreq__DOT__data_p2;
        QData/*63:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq__DOT____Vlvbound_h009b1c58__0;
        QData/*63:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq__DOT____Vxrand___0;
        QData/*35:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__q_buf;
        QData/*35:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__q_tmp;
        QData/*35:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__dout_buf;
        QData/*63:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq_data;
        QData/*63:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rreq__DOT__data_p1;
        QData/*63:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rreq__DOT__data_p2;
        QData/*63:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq__DOT____Vlvbound_h009b1c58__0;
        QData/*63:0*/ axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq__DOT____Vxrand___0;
        QData/*34:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__if_din;
        QData/*34:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__q_buf;
        QData/*34:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__q_tmp;
        QData/*34:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__dout_buf;
        QData/*33:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rdata__DOT__s_data;
        QData/*33:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rdata__DOT__data_p1;
        QData/*33:0*/ __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__rs_rdata__DOT__data_p2;
        VlUnpacked<SData/*9:0*/, 1024> __PVT__axi4_tester_inst__DOT__addr_U__DOT__axi4_tester_addr_rom_U__DOT__ram;
        VlUnpacked<IData/*31:0*/, 1024> __PVT__axi4_tester_inst__DOT__test_data_V_U__DOT__axi4_tester_test_data_V_rom_U__DOT__ram;
        VlUnpacked<QData/*63:0*/, 5> __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_wreq__DOT__mem;
        VlUnpacked<QData/*35:0*/, 256> __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__buff_wdata__DOT__mem;
        VlUnpacked<CData/*1:0*/, 15> __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp__DOT__mem;
        VlUnpacked<CData/*1:0*/, 5> __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__fifo_resp_to_user__DOT__mem;
        VlUnpacked<CData/*7:0*/, 5> __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_write__DOT__bus_equal_gen__DOT__fifo_burst__DOT__mem;
        VlUnpacked<QData/*63:0*/, 5> __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rreq__DOT__mem;
        VlUnpacked<QData/*34:0*/, 256> __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__buff_rdata__DOT__mem;
        VlUnpacked<CData/*1:0*/, 15> __PVT__axi4_tester_inst__DOT__axi4_tester_data_in_out_V_m_axi_U__DOT__bus_read__DOT__fifo_rctl__DOT__mem;
        VlUnpacked<IData/*31:0*/, 1024> __PVT__axi4_tester_inst__DOT__data_from_mem_V_U__DOT__axi4_tester_data_from_mem_V_ram_U__DOT__ram;
        VlUnpacked<IData/*31:0*/, 16384> __PVT__axi_ram_inst__DOT__mem;
    };

    // INTERNAL VARIABLES
    Vtb_axi4_ram__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtb_axi4_ram_tb_axi4_ram() = default;
    ~Vtb_axi4_ram_tb_axi4_ram() = default;
    void ctor(Vtb_axi4_ram__Syms* symsp, const char* namep);
    void dtor();
    VL_UNCOPYABLE(Vtb_axi4_ram_tb_axi4_ram);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
